name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ftp.hyenathedesignerbe.webhosting.be         # The FTP server URL
        username: ${{ secrets.FTP_USERNAME }}      # Your FTP username (from repository secrets)
        password: ${{ secrets.FTP_PASSWORD }}      # Your FTP password (from repository secrets)
        local-dir: ./                              # Directory to upload (the repository root)
        server-dir: /public_html                 # Directory on your FTP server (adjust if needed)
